### ISSUE TITLE
finish persistence landscape implementation

### ISSUE THREAD

**Issue by rrrlw** [tdaverse/ggtda#16]
basic feature of persistence landscape (`stat_persistence(diagram = "landscape")`) has been implemented, following would help complete implementation:

- [ ] inclusion of diagonal lines within stat/geom to mimic a landscape?
- [ ] example added to README
- [ ] use described in more detail in a ggtda vignette

Edit:
- [ ] add multiple persistence landscapes (exported function + shortcut stat)

**Comment by corybrunson** [comment]
The more advanced need here is to write a new stat layer to "add" multiple persistence landscapes; see [Bubenik and Paweł (2016)](https://hal.inria.fr/hal-01258875/file/PersistenceLandscapes_arxiv_v3.pdf) for the theory. One way to do this would be via a grouping variable in a data frame of birth–death pairs that identifies the pairs calculated for each "sample", i.e. it would all be done internally by the stat layer. Another way would be to export a function that could perform this operation and then write a stat that recognizes its output (which would then be a different kind of "persistence data"). I haven't actually used this technique, so i would plan to go both ways: Write the exported function, but also have a shortcut stat use it internally. This would give the most control to the user. Indeed, the exported function could also output the simple landscape for the birth–death pairs obtained from a single PH operation.

Note: In principle, the adding of landscapes may be compatible with any of the three layouts (flat, diagonal, landscape), but it seems reasonable to discourage its use with diagonal and (especially) flat. But that may become clearer with the implementation.

**Comment by rrrlw** [comment]
I see, thanks! I've edited the checklist above to reflect this.

**Comment by corybrunson** [comment]
This has been done and refined in recent commits, notably ee2d58e86901f0f609029be90c20f66949b97db3, 972acecfe30175c032a24cc090b04e9d3a5ea0ef, 3458c8fb9c6f4801dc33f35d2c8a8ba71ab5a9fd, and 36d425039a10ab36ef2c6bd152df37e4a232c54d.
